---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: NetApp Console 에 포함된 기능 및 데이터 서비스의 최신 변경 사항에 대해 알아보세요. 
---
= NetApp Console 의 최근 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 에 포함된 기능 및 데이터 서비스의 최신 변경 사항에 대해 알아보세요.  전체 릴리스 내역을 보려면 다음으로 이동하세요.link:release-notes-index.html["릴리스 노트 전체 세트"] 각 개별 서비스에 대해.



== 관리 기능

이 섹션에서는 NetApp Console 관리 기능과 관련된 새로운 기능에 대해 설명합니다. 여기에는 조직, 식별 및 액세스, 콘솔 에이전트, 클라우드 공급자 자격 증명 등이 포함됩니다.



== 알림



== ONTAP 용 Amazon FSx



== Amazon S3 스토리지



== Azure Blob 저장소



== Azure NetApp Files



== 백업 및 복구



== 데이터 분류



== Cloud Volumes ONTAP



== 복사 및 동기화



== 디지털 어드바이저



== Licenses and subscriptions



=== 2025년 10월 6일



==== BlueXP 는 이제 NetApp Console 입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경에서 NetApp 스토리지와 NetApp Data Services 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 사항에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console 릴리스 노트"] .



=== 2025년 3월 10일



==== 구독을 제거하는 기능

구독을 취소한 경우 이제 디지털 지갑에서 구독을 제거할 수 있습니다.



==== 마켓플레이스 구독에 사용된 용량 보기

PAYGO 구독을 볼 때 이제 구독의 소비 용량을 볼 수 있습니다.



=== 2025년 2월 10일

BlueXP digital wallet 사용 편의성을 위해 재설계되었으며, 이제 추가적인 구독 및 라이선스 관리 기능을 제공합니다.



==== 새로운 개요 대시보드

디지털 지갑 홈페이지에는 NetApp 라이선스와 Marketplace 구독에 대한 업데이트된 대시보드가 ​​있으며, 특정 서비스, 라이선스 유형 및 필요한 작업에 대한 자세한 정보를 볼 수 있습니다.



==== 자격 증명에 대한 구독 구성

이제 BlueXP digital wallet 사용하면 공급자 자격 증명에 대한 구독을 구성할 수 있습니다. 일반적으로 마켓플레이스 구독이나 연간 계약을 처음 신청할 때 이 작업을 수행합니다. 이전에는 구독 자격 증명을 변경하는 작업은 자격 증명 페이지에서만 수행할 수 있었습니다.



==== 구독을 조직과 연결

이제 디지털 지갑에서 구독이 연결된 조직을 직접 업데이트할 수 있습니다.



==== Cloud Volume ONTAP 라이선스 관리

이제 홈페이지나 *직접 라이선스* 탭을 통해 Cloud Volumes ONTAP 라이선스를 관리할 수 있습니다. *마켓플레이스 구독* 탭을 사용하여 구독 정보를 확인하세요.



=== 2024년 3월 5일



==== BlueXP disaster recovery

이제 BlueXP digital wallet 사용하여 BlueXP disaster recovery 라이선스를 관리할 수 있습니다. 라이선스를 추가하고, 라이선스를 업데이트하고, 라이선스 용량에 대한 세부 정보를 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["BlueXP 데이터 서비스에 대한 라이선스를 관리하는 방법을 알아보세요."]



=== 2023년 7월 30일



==== 사용 보고서 개선

Cloud Volumes ONTAP 사용 보고서에 다음과 같은 여러 가지 개선 사항이 적용되었습니다.

* 이제 TiB 단위가 열 이름에 포함됩니다.
* 이제 일련 번호에 대한 새로운 _노드_ 필드가 포함되었습니다.
* 이제 스토리지 VM 사용 보고서에 새로운 _워크로드 유형_ 열이 포함되었습니다.
* 이제 작업 환경 이름이 저장소 VM 및 볼륨 사용 보고서에 포함됩니다.
* 볼륨 유형 _파일_은 이제 _기본(읽기/쓰기)_으로 표시됩니다.
* 볼륨 유형 _secondary_는 이제 _Secondary (DP)_로 표시됩니다.


사용 보고서에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["사용 보고서 다운로드"] .



== 재해 복구



== E-시리즈 시스템



== 수명주기 계획



== 에지 캐싱

엣지 캐싱 서비스는 2024년 8월 7일에 종료되었습니다.



== Google Cloud NetApp Volumes



== 구글 클라우드 스토리지



== Keystone



== 쿠버네티스

Kubernetes 클러스터 검색 및 관리에 대한 지원은 2024년 8월 7일에 종료되었습니다.



== 이주 보고서

2024년 8월 7일에 이주 보고 서비스가 종료되었습니다.



== 온프레미스 ONTAP 클러스터



== 운영 회복력

운영 복원력 기능은 2025년 8월 22일에 제거되었습니다.



== 랜섬웨어 복원력



== 개선

2024년 4월 22일에 복구 서비스가 종료되었습니다.



== 복제



== 소프트웨어 업데이트



== StorageGRID



== 클라우드 티어링



=== 2025년 10월 6일



==== BlueXP tiering 이제 NetApp Cloud Tiering 입니다.

BlueXP tiering 이 NetApp Cloud Tiering 으로 변경되었습니다.



==== BlueXP 는 이제 NetApp Console 입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경에서 NetApp 스토리지와 NetApp Data Services 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console 릴리스 노트"] .



=== 2023년 8월 9일



==== 버킷 이름에 사용자 정의 접두사를 사용하세요

이전에는 버킷 이름을 정의할 때 기본 "fabric-pool" 접두사(예: _fabric-pool-bucket1_)를 사용해야 했습니다.  이제 버킷 이름을 지정할 때 사용자 지정 접두사를 사용할 수 있습니다.  이 기능은 Amazon S3에 데이터를 계층화할 때만 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["자세히 알아보기"] .



==== 모든 BlueXP 커넥터에서 클러스터 검색

사용자 환경의 모든 스토리지 시스템을 관리하기 위해 여러 개의 커넥터를 사용하는 경우, 계층화를 구현하려는 일부 클러스터가 서로 다른 커넥터에 있을 수 있습니다.  특정 클러스터를 관리하는 커넥터가 무엇인지 확실하지 않은 경우 Cloud Tiering을 사용하여 모든 커넥터를 검색할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["자세히 알아보기"] .



=== 2023년 7월 4일



==== 비활성 데이터를 전송하기 위해 대역폭을 조정합니다.

클라우드 티어링을 활성화하면 ONTAP 무제한의 네트워크 대역폭을 사용하여 클러스터의 볼륨에서 비활성 데이터를 개체 스토리지로 전송할 수 있습니다.  계층화된 트래픽이 일반 사용자 작업 부하에 영향을 미치는 경우 전송 중에 사용할 수 있는 대역폭 양을 조절할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["자세히 알아보기"] .



==== 알림 센터에 표시되는 티어링 이벤트

클러스터가 콜드 데이터의 20% 미만을 계층화하는 경우(데이터를 계층화하지 않는 클러스터 포함) 계층화 이벤트 "클러스터 <이름>에서 개체 스토리지로 추가 데이터를 계층화하여 스토리지 효율성을 높이세요"가 이제 알림으로 표시됩니다.

이 알림은 귀하의 시스템 효율성을 높이고 저장 비용을 절감하는 데 도움이 되는 "권장 사항"입니다. 링크를 제공합니다 https://www.netapp.com/data-services/tiering/tco-calculator/["클라우드 티어링 총 소유 비용 및 절감 계산기"^] 비용 절감액을 계산하는 데 도움이 됩니다.



== 볼륨 캐싱



== 작업량 공장



=== 2025년 10월 6일



==== BlueXP workload factory NetApp Workload Factory 변경되었습니다.

BlueXP 데이터 인프라 관리에 있어서의 역할을 더 잘 반영하도록 이름이 바뀌고 재설계되었습니다.  결과적으로 BlueXP workload factory NetApp Workload Factory 로 이름이 변경되었습니다.



==== MCP와 Ask Me 통합

Workload Factory의 AI 어시스턴트인 Ask Me는 MCP(Model Context Protocol)와 통합되어 있습니다.  Ask Me는 MCP를 사용하여 외부 환경과 안전하게 인터페이스하고 API 도구를 쿼리하여 특정 스토리지 환경에 맞춤형 응답을 제공합니다.



=== 2025년 10월 5일



==== 저장소에 대한 새로운 알림

NetApp Workload Factory 알림 서비스에는 스토리지에 대한 잘 설계된 문제에 대한 알림이 포함되어 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory 에 대한 알림"]



=== 2025년 9월 9일



==== 저장소에 대한 새로운 알림

BlueXP workload factory 알림 서비스에는 스토리지의 자동 용량 관리에 대한 알림이 포함되어 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP workload factory 에 대한 알림"]
