---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: NetApp 콘솔에 포함된 기능 및 데이터 서비스의 최신 변경 사항에 대해 알아보세요. 
---
= NetApp 콘솔의 최근 변경 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 콘솔에 포함된 기능 및 데이터 서비스의 최신 변경 사항에 대해 알아보세요.  전체 릴리스 내역을 보려면 다음으로 이동하세요.link:release-notes-index.html["릴리스 노트 전체 세트"] 각 개별 서비스에 대해.



== 관리 기능

이 섹션에서는 NetApp 콘솔 관리 기능과 관련된 새로운 기능에 대해 설명합니다. 여기에는 조직, 식별 및 액세스, 콘솔 에이전트, 클라우드 공급자 자격 증명 등이 포함됩니다.

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/console-setup-admin/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 알림



=== 2025년 10월 6일



==== BlueXP alerts 이제 ONTAP 알림입니다.

BlueXP alerts ​​ONTAP 알림으로 이름이 변경되었습니다.

NetApp 콘솔 왼쪽 탐색 모음에서 *저장소* > *알림*을 선택하여 액세스할 수 있습니다.



==== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp 콘솔 릴리스 노트"] .



=== 2024년 10월 7일



==== BlueXP alerts 목록 페이지

용량이 적거나 성능이 낮은 ONTAP 클러스터를 빠르게 식별하고, 가용성 범위를 측정하고, 보안 위험을 파악할 수 있습니다. 용량, 성능, 보호, 가용성, 보안 및 구성과 관련된 알림을 볼 수 있습니다.



==== 알림 세부 정보

알림 세부 정보를 자세히 살펴보고 권장 사항을 찾을 수 있습니다.



==== ONTAP 시스템 관리자에 연결된 클러스터 세부 정보 보기

BlueXP alerts 사용하면 ONTAP 스토리지 환경과 관련된 알림을 보고 ONTAP System Manager에 연결된 세부 정보를 자세히 살펴볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["BlueXP alerts 에 대해 알아보세요"] .



== ONTAP 용 Amazon FSx

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/console-fsx-ontap/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Amazon S3 스토리지

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-managment-s3-storage/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Azure Blob 저장소

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-blob-storage/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Azure NetApp Files

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-azure-netapp-files/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 백업 및 복구

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/data-services-backup-recovery/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 데이터 분류

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/data-services-data-classification/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Cloud Volumes ONTAP

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-cloud-volumes-ontap/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 복사 및 동기화

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/data-services-copy-sync/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 디지털 어드바이저



=== 2025년 10월 6일



==== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp 콘솔 릴리스 노트"] .



=== 2025년 8월 6일



==== 지원 권한 스위치

이제 지원 자격이 있는 Brocade Fibre Channel SAN 스위치에 대한 정보를 볼 수 있습니다. 여기에는 스위치 모델, 일련 번호, 지원 상태에 대한 세부 정보가 포함됩니다. link:https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html["지원 권한이 있는 스위치를 보는 방법을 알아보세요"] .



==== RSS AutoSupport 데이터에 대한 임계값

AutoSupport 위젯의 최근 전송 중지된 RSS(RSS) 제한이 시스템이 RSS로 표시되기 전까지 48시간(2일)에서 216시간(9일)으로 연장되었습니다. 이는 주간 AutoSupport 데이터만 전송하는 StorageGRID 와 같은 플랫폼을 수용하기 위해 수행됩니다.



==== Digital Advisor API 카탈로그의 더 이상 사용되지 않는 API 섹션

Digital Advisor API 카탈로그에서 더 이상 사용되지 않는 새로운 API 섹션을 사용할 수 있습니다. 여기에는 지원 중단이 예정된 API, 지원 중단 일정 및 대체 API가 나열되어 있습니다.



==== 용량 예측 V2 및 지원 종료 API 모듈 사용 중단

용량 예측 V2 및 지원 종료 API 모듈은 사용 중단될 예정입니다. 더 이상 지원되지 않는 API에 액세스하거나 지원 중단 일정과 대체 API에 대해 알아보려면 *API 서비스 -> 찾아보기 -> 더 이상 지원되지 않는 API*로 이동하세요.



=== 2025년 7월 9일



==== 업그레이드 어드바이저

* ONTAP 업그레이드 계획을 간소화하고 잠재적인 차단 요소나 경고를 해결하기 위해 업그레이드 어드바이저 계획에 다중 형식 다운로드 옵션이 포함되었습니다.  이제 업그레이드 어드바이저 플랜을 Excel, PDF, JSON 형식으로 다운로드할 수 있습니다.
* 업그레이드 어드바이저 계획의 Excel 형식에는 다음과 같은 개선 사항이 적용되었습니다.
+
** 클러스터에서 수행된 사전 검사를 보고, 결과에 "통과", "실패", "건너뜀"과 같은 표시기를 표시할 수 있습니다.  이렇게 하면 ONTAP 업그레이드를 완료하기 위해 클러스터가 최적의 상태가 됩니다.
** ONTAP 대상 버전과 함께 제공된 버전과 함께 클러스터에 적용 가능한 권장 최신 펌웨어 업데이트를 볼 수 있습니다.
** SAN 클러스터에 대한 상호 운용성 검사를 제공하는 새로운 탭이 포함되었습니다.  선택한 대상 ONTAP 버전에 대해 지원되는 호스트 OS 버전을 볼 수 있습니다.






== 라이센스 및 구독



=== 2025년 10월 6일



==== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 사항에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp 콘솔 릴리스 노트"] .



=== 2025년 3월 10일



==== 구독을 제거하는 기능

구독을 취소한 경우 이제 디지털 지갑에서 구독을 제거할 수 있습니다.



==== 마켓플레이스 구독에 사용된 용량 보기

PAYGO 구독을 볼 때 이제 구독의 소비 용량을 볼 수 있습니다.



=== 2025년 2월 10일

BlueXP digital wallet 사용 편의성을 위해 재설계되었으며, 이제 추가적인 구독 및 라이선스 관리 기능을 제공합니다.



==== 새로운 개요 대시보드

디지털 지갑 홈페이지에는 NetApp 라이선스와 Marketplace 구독에 대한 업데이트된 대시보드가 ​​있으며, 특정 서비스, 라이선스 유형 및 필요한 작업에 대한 자세한 정보를 볼 수 있습니다.



==== 자격 증명에 대한 구독 구성

이제 BlueXP digital wallet 사용하면 공급자 자격 증명에 대한 구독을 구성할 수 있습니다. 일반적으로 마켓플레이스 구독이나 연간 계약을 처음 신청할 때 이 작업을 수행합니다. 이전에는 구독 자격 증명을 변경하는 작업은 자격 증명 페이지에서만 수행할 수 있었습니다.



==== 구독을 조직과 연결

이제 디지털 지갑에서 구독이 연결된 조직을 직접 업데이트할 수 있습니다.



==== Cloud Volume ONTAP 라이선스 관리

이제 홈페이지나 *직접 라이선스* 탭을 통해 Cloud Volumes ONTAP 라이선스를 관리할 수 있습니다. *마켓플레이스 구독* 탭을 사용하여 구독 정보를 확인하세요.



=== 2024년 3월 5일



==== BlueXP disaster recovery

이제 BlueXP digital wallet 사용하여 BlueXP disaster recovery 라이선스를 관리할 수 있습니다. 라이선스를 추가하고, 라이선스를 업데이트하고, 라이선스 용량에 대한 세부 정보를 볼 수 있습니다.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["BlueXP 데이터 서비스에 대한 라이선스를 관리하는 방법을 알아보세요."]



=== 2023년 7월 30일



==== 사용 보고서 개선

Cloud Volumes ONTAP 사용 보고서에 다음과 같은 여러 가지 개선 사항이 적용되었습니다.

* 이제 TiB 단위가 열 이름에 포함됩니다.
* 이제 일련 번호에 대한 새로운 _노드_ 필드가 포함되었습니다.
* 이제 스토리지 VM 사용 보고서에 새로운 _워크로드 유형_ 열이 포함되었습니다.
* 이제 작업 환경 이름이 저장소 VM 및 볼륨 사용 보고서에 포함됩니다.
* 볼륨 유형 _파일_은 이제 _기본(읽기/쓰기)_으로 표시됩니다.
* 볼륨 유형 _secondary_는 이제 _Secondary (DP)_로 표시됩니다.


사용 보고서에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["사용 보고서 다운로드"] .



== 재해 복구

<stdin>에 해결되지 않은 지시어가 있습니다. - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-disaster-recovery/main/release-notes/dr-whats-new.adoc [tag=whats-new,leveloffset=+1]



== E-시리즈 시스템

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-e-series/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 수명주기 계획



=== 2025년 10월 6일



==== BlueXP economic efficiency 이제 수명 주기 계획입니다.

BlueXP economic efficiency 수명 주기 계획으로 이름이 바뀌었습니다.

NetApp 콘솔 왼쪽 탐색 모음에서 *스토리지* > *수명주기 계획*을 선택하여 액세스할 수 있습니다.



==== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp 콘솔 릴리스 노트"] .



=== 2024년 5월 15일



==== 장애인용 기능

일부 BlueXP economic efficiency 기능이 일시적으로 비활성화되었습니다.

* 기술 업데이트
* 용량 추가




=== 2024년 3월 14일



==== 기술 갱신 옵션

기존 자산이 있고 기술을 업데이트해야 하는지 여부를 확인하려면 BlueXP 경제적 효율성 기술 새로 고침 옵션을 사용할 수 있습니다. 현재 작업 부하에 대한 간략한 평가를 검토하고 권장 사항을 받을 수 있으며, 지난 90일 이내에 NetApp 에 ​​AutoSupport 로그를 보낸 경우 해당 서비스에서 작업 부하가 새 하드웨어에서 어떻게 수행되는지 확인하기 위한 작업 부하 시뮬레이션을 제공할 수 있습니다.

시뮬레이션에서 워크로드를 추가하고 기존 워크로드를 제외할 수도 있습니다.

이전에는 자산을 평가하고 기술 갱신이 필요한지 여부만 파악할 수 있었습니다.

이 기능은 이제 왼쪽 탐색 메뉴의 기술 새로 고침 옵션에 포함되었습니다.

자세히 알아보세요 https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["기술 갱신 평가"] .



== 에지 캐싱

엣지 캐싱 서비스는 2024년 8월 7일에 종료되었습니다.



== Google Cloud NetApp Volumes

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-google-cloud-netapp-volumes/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 구글 클라우드 스토리지

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-google-cloud-storage/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== Keystone



=== 2025년 10월 6일



==== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

2ef72cc8a56fc5999e258b450b9fca24



=== 2025년 9월 22일



==== 알람 모니터링 추가

BlueXP 의 Keystone 대시보드에는 이제 구독 전반의 알림과 모니터를 관리하기 위한 *모니터링* 탭이 포함되었습니다. 이 새로운 탭을 사용하면 다음 작업을 수행할 수 있습니다.

* 시스템 생성 알림과 사용자 정의 알림(용량 사용 및 구독 만료)을 포함한 활성 알림을 보고 해결합니다.
* 용량 사용 및 구독 만료 이벤트를 추적하기 위해 알림 모니터를 만듭니다.


자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alerts.html["알림 및 모니터 보기 및 관리"] .



==== 간소화된 성능 서비스 수준 보기

*구독* 탭에서 별도 탭에서 확장 가능한 보기로 이동된 성능 서비스 수준 정보를 볼 수 있습니다. 각 구독에 대한 만료일을 보려면 *만료일* 열 옆에 있는 아래쪽 화살표를 클릭하세요. 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["Keystone 구독에 대한 세부 정보 보기"] .



=== 2025년 8월 28일



==== 새로운 열을 통해 향상된 논리적 사용 추적

FabricPool 볼륨에 대한 Keystone 소비량 추적을 강화하기 위해 새로운 열인 '전체 발자국'이 추가되었습니다.

* * BlueXP 의 Keystone 대시보드 *: *자산* 탭의 *클러스터 볼륨* 탭에서 *총 설치 공간* 열을 볼 수 있습니다.
* * Digital Advisor*: *볼륨 및 개체* 탭의 *볼륨 세부 정보* 탭에서 *총 공간* 열을 볼 수 있습니다.


이 열은 성능 및 콜드 계층의 데이터를 포함하여 FabricPool 계층화를 사용하는 볼륨의 총 논리적 설치 공간을 표시하므로 Keystone 소비량을 정확하게 계산할 수 있습니다.



== 쿠버네티스

Kubernetes 클러스터 검색 및 관리에 대한 지원은 2024년 8월 7일에 종료되었습니다.



== 이주 보고서

2024년 8월 7일에 이주 보고 서비스가 종료되었습니다.



== 온프레미스 ONTAP 클러스터

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-management-ontap-onprem/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 운영 회복력

운영 복원력 기능은 2025년 8월 22일에 제거되었습니다.



== 랜섬웨어 복원력

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/data-services-ransomware-resilience/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 개선

2024년 4월 22일에 복구 서비스가 종료되었습니다.



== 복제

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/data-services-replication/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 소프트웨어 업데이트

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/console-software-updates/main/release-notes/whats-new.adoc [tag=whats-new,leveloffset=+1]



== StorageGRID

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/storage-managment-storagegrid/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 클라우드 티어링

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/data-service-cloud-tiering/main/whats-new.adoc [tag=whats-new,leveloffset=+1]



== 볼륨 캐싱

<stdin>에 해결되지 않은 지시어가 있습니다 - include:: https://raw.githubusercontent.com/NetAppDocs/console-volume-caching/main/release-notes/cache-whats-new.adoc [tag=whats-new,leveloffset=+1]



== 작업량 공장



=== 2025년 6월 29일



==== 데이터베이스에 대한 권한 업데이트

다음 권한은 이제 데이터베이스에 대해 _읽기 전용_ 모드로 사용 가능합니다. `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



==== BlueXP workload factory 알림 서비스 지원

BlueXP workload factory 알림 서비스를 사용하면 워크로드 팩토리가 BlueXP alerts 서비스나 Amazon SNS 주제에 알림을 보낼 수 있습니다.  BlueXP alerts 에 전송된 알림은 BlueXP alerts 패널에 표시됩니다.  워크로드 팩토리가 Amazon SNS 주제에 알림을 게시하면 해당 주제의 구독자(예: 사람 또는 다른 애플리케이션)는 해당 주제에 대해 구성된 엔드포인트(예: 이메일 또는 SMS 메시지)에서 알림을 받습니다.

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP workload factory 알림 구성"]



=== 2025년 5월 4일



==== CloudShell 자동완성 지원

BlueXP workload factory CloudShell을 사용하면 명령을 입력하고 Tab 키를 눌러 사용 가능한 옵션을 볼 수 있습니다.  여러 가지 가능성이 존재하는 경우 CLI는 제안 목록을 표시합니다.  이 기능은 오류를 최소화하고 명령 실행 속도를 높여 생산성을 향상시킵니다.



==== 업데이트된 권한 용어

워크로드 팩토리 사용자 인터페이스와 설명서에서는 이제 읽기 권한을 나타내는 데 "읽기 전용"을 사용하고 자동화 권한을 나타내는 데 "읽기/쓰기"를 사용합니다.



=== 2025년 3월 30일



==== CloudShell은 ONTAP CLI 명령에 대한 AI 생성 오류 응답을 보고합니다.

CloudShell을 사용하면 ONTAP CLI 명령을 실행하고 오류가 발생할 때마다 오류에 대한 설명, 오류 원인, 자세한 해결 방법이 포함된 AI 생성 오류 응답을 받을 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용하세요"]



==== iam:SimulatePermissionPolicy 권한 업데이트

이제 관리할 수 있습니다 `iam:SimulatePrincipalPolicy` AWS 계정 자격 증명을 추가하거나 GenAI 워크로드와 같은 새로운 워크로드 기능을 추가할 때 워크로드 팩토리 콘솔에서 권한을 부여합니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]



=== 2025년 2월 2일



==== BlueXP workload factory 콘솔에서 CloudShell 사용 가능

CloudShell은 BlueXP workload factory 콘솔의 어느 곳에서나 사용할 수 있습니다.  CloudShell을 사용하면 BlueXP 계정에서 제공한 AWS 및 ONTAP 자격 증명을 사용하여 셸과 유사한 환경에서 AWS CLI 명령이나 ONTAP CLI 명령을 실행할 수 있습니다.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShell을 사용하세요"]



==== 데이터베이스에 대한 권한 업데이트

이제 데이터베이스의 _read_ 모드에서 다음 권한을 사용할 수 있습니다. `iam:SimulatePrincipalPolicy` .

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["권한 참조 변경 로그"]
