= 콘솔 에이전트 4.3.0
:allow-uri-read: 




=== 콘솔 에이전트 4.3.0

4.3.0 버전은 표준 모드와 제한 모드를 모두 지원합니다.

이 콘솔 에이전트 릴리스에는 보안 개선, 버그 수정 및 다음 기능이 포함되어 있습니다.

.콘솔 에이전트의 네트워크 연결을 검증할 수 있는 기능
이제 NetApp Console 에서 연결된 콘솔 에이전트의 네트워크 연결을 직접 확인할 수 있습니다. 이 기능은 콘솔 에이전트의 연결 상태를 확인하고 문제를 해결하는 데 도움이 됩니다.

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["콘솔 에이전트에 대한 구성 검사를 실행하는 방법을 알아보세요."]



=== NetApp Console 관리

이 릴리스에는 다음이 포함됩니다.

.NetApp Console 에서 페더레이션 그룹에 대한 역할 기반 액세스
NetApp Console 페더레이션 그룹(예: Active Directory 그룹)에 역할을 할당하는 기능을 지원하므로 관리자는 조직의 ID 공급자(IdP)의 그룹 멤버십을 기반으로 사용자 온보딩 및 오프보딩을 자동화할 수 있습니다. 이 기능은 관리 부담을 줄이고 그룹 멤버십이 변경될 때 콘솔 액세스 권한을 즉시 업데이트하여 안전하고 일관된 액세스를 보장합니다.

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["조직 구성원에게 연합 그룹에 대한 액세스 권한을 부여하는 방법을 알아보세요."]

.NetApp Console 제한 모드일 때 페더레이션 지원
이제 제한 모드로 설정된 NetApp Console 조직에 대해 페더레이션을 활성화할 수 있습니다. 이를 통해 사용자는 회사 자격 증명을 사용하여 콘솔에 로그인하는 동시에 제한 모드의 보안 이점을 유지할 수 있습니다.

.읽기 전용 모드
NetApp Console 조직을 읽기 전용 모드로 설정할 수 있습니다. 읽기 전용 모드에서는 사용자가 리소스와 설정을 볼 수는 있지만 변경할 수는 없습니다. 조직 관리자 또는 최고 관리자는 조직에 대해 읽기 전용 모드를 활성화할 수 있습니다. 읽기 전용 모드가 활성화된 경우, 관리자 권한을 가진 사용자는 필요에 따라 변경 작업을 수행하기 위해 수동으로 권한을 상승시켜야 합니다.

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["콘솔 조직에 대해 읽기 전용 모드를 활성화하는 방법을 알아보세요."]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings["조직이 읽기 전용 모드일 때 자신의 역할을 강화하는 방법을 알아보세요."]
