= S3 구성 ONTAP 시스템의 버킷에 볼륨을 백업하는 지원이 추가되었습니다.
:allow-uri-read: 


[IMPORTANT]
====
* 중요한 보안 강화로 인해 이제 커넥터에는 퍼블릭 클라우드 환경 내에서 백업 및 복구 리소스를 관리하기 위해 추가 엔드포인트에 대한 아웃바운드 인터넷 액세스가 필요합니다.  방화벽의 "허용" 목록에 이 엔드포인트가 추가되지 않은 경우 UI에 "서비스를 사용할 수 없음" 또는 "서비스 상태를 확인하지 못했습니다"라는 오류가 표시됩니다.
+
\ https://netapp-cloud-account.auth0.com

* Cloud Volumes ONTAP 과 BlueXP backup and recovery 번들로 제공하는 "CVO Professional" 패키지를 사용하는 경우 이제 백업 및 복구 PAYGO 구독이 필요합니다.  과거에는 이런 것이 필요하지 않았습니다.  적격 Cloud Volumes ONTAP 시스템의 백업 및 복구 구독에는 요금이 부과되지 않지만, 새 볼륨에 백업을 구성할 때는 구독이 필요합니다.


====


=== S3 구성 ONTAP 시스템의 버킷에 볼륨을 백업하는 지원이 추가되었습니다.

이제 Simple Storage Service(S3)에 맞게 구성된 ONTAP 시스템을 사용하여 볼륨을 개체 스토리지에 백업할 수 있습니다.  이는 온프레미스 ONTAP 시스템과 Cloud Volumes ONTAP 시스템 모두에서 지원됩니다.  이 구성은 클라우드 배포와 인터넷 접속이 없는 온프레미스 위치("개인" 모드 배포)에서 지원됩니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["자세히 알아보기"] .



=== 이제 보호된 볼륨의 기존 스냅샷을 백업 파일에 포함할 수 있습니다.

과거에는 최신 스냅샷 복사본으로 시작하는 대신 읽기-쓰기 볼륨의 기존 스냅샷 복사본을 초기 백업 파일에 개체 스토리지에 포함할 수 있었습니다.  읽기 전용 볼륨(데이터 보호 볼륨)의 기존 스냅샷 복사본은 백업 파일에 포함되지 않았습니다.  이제 "DP" 볼륨의 백업 파일에 이전 스냅샷 사본을 포함하도록 선택할 수 있습니다.

백업 마법사는 백업 단계의 마지막에 "기존 스냅샷"을 선택할 수 있는 메시지를 표시합니다.



=== BlueXP backup and recovery 더 이상 미래에 추가되는 볼륨의 자동 백업을 지원하지 않습니다.

이전에는 백업 마법사에서 상자를 선택하여 선택한 백업 정책을 클러스터에 추가되는 모든 향후 볼륨에 적용할 수 있었습니다.  이 기능은 사용자 피드백과 이 기능의 사용 부족으로 인해 제거되었습니다.  클러스터에 추가된 모든 새 볼륨에 대한 백업을 수동으로 활성화해야 합니다.



=== 작업 모니터링 페이지가 새로운 기능으로 업데이트되었습니다.

작업 모니터링 페이지에서는 이제 3-2-1 백업 전략과 관련된 자세한 정보를 제공합니다.  이 서비스는 백업 전략과 관련된 추가적인 알림도 제공합니다.

"백업 수명 주기" 유형 필터의 이름이 "보존"으로 변경되었습니다.  이 필터를 사용하면 백업 수명 주기를 추적하고 모든 백업 사본의 만료일을 파악할 수 있습니다.  "보존" 작업 유형은 BlueXP backup and recovery 로 보호되는 볼륨에서 시작된 모든 스냅샷 삭제 작업을 캡처합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["업데이트된 Job Monitor에 대해 자세히 알아보세요"] .
