= ONTAP 데이터에 대한 새로운 정책 관리
:allow-uri-read: 




=== ONTAP 데이터에 대한 새로운 정책 관리

이 릴리스에는 ONTAP 데이터에 대한 사용자 정의 스냅샷 정책, 복제 정책 및 개체 스토리지 백업 정책을 UI 내에서 생성할 수 있는 기능이 포함되어 있습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["정책에 대해 자세히 알아보세요"] .



=== ONTAP S3 개체 스토리지의 볼륨에서 파일 및 폴더 복원 지원

이전에는 볼륨이 ONTAP S3 개체 스토리지에 백업된 경우 "찾아보기 및 복원" 기능을 사용하여 파일과 폴더를 복원할 수 없었습니다.  이 릴리스에서는 그러한 제한이 제거되었습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["데이터 복원에 대해 자세히 알아보세요"] .



=== 표준 저장소에 먼저 쓰는 대신 백업 데이터를 즉시 보관할 수 있는 기능

이제 표준 클라우드 스토리지에 데이터를 쓰는 대신 백업 파일을 즉시 보관 스토리지로 보낼 수 있습니다.  이 기능은 클라우드 백업 데이터에 거의 액세스할 필요가 없는 사용자나 테이프 환경으로 백업을 대체하는 사용자에게 특히 유용할 수 있습니다.



=== SnapLock 볼륨 백업 및 복원에 대한 추가 지원

백업 및 복구는 이제 SnapLock Compliance 또는 SnapLock Enterprise 보호 모드를 사용하여 구성된 FlexVol 및 FlexGroup 볼륨을 모두 백업할 수 있습니다.  이 지원을 받으려면 클러스터에서 ONTAP 9.14 이상을 실행해야 합니다.  ONTAP 버전 9.11.1부터 SnapLock Enterprise 모드를 사용하여 FlexVol 볼륨을 백업하는 기능이 지원되었습니다.  이전 ONTAP 릴리스에서는 SnapLock 보호 볼륨 백업을 지원하지 않습니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["ONTAP 데이터 보호에 대해 자세히 알아보세요"] .
